# To build the images
# docker-compose build

# To run the containers
# docker-compose up

# Which version of the docker-compose API to use
version: '2'

services:

  # api server
  api:
    container_name: api
    build: ./api

  # client container
  client:
    container_name: client
    build: ./client
