# To build the images
# docker-compose build

# To run the containers
# docker-compose up

# Which version of the docker-compose API to use
version: '2'

services:

  # api server
  api:
    build: ./api
    container_name: api
    depends_on:
      - db

  # client container
  client:
    container_name: client
    build: ./client

  # database
  db:
    container_name: db
    image: mongo:3.0
    ports:
      - 27019:27019

  # run this container to make a backup of mongodb's contents
  # it will overwrite the backup inside of db/data/
  #
  # use: docker-compose run --rm backup-db
  #
  # then: remember to `git add` and `git commit` the new database dump, give it a good message
  #
  backup-db:
    command: /db/backup.sh
    container_name: 'backup-db'
    depends_on:
      - db
    image: mongo:3.0
    volumes:
      - ./db/:/db/

  # run this container to make a backup of mongodb's contents
  # it will overwrite the backup inside of db/data/
  #
  # use: docker-compose run --rm restore-db
  #
  restore-db:
    command: /db/restore.sh
    container_name: 'restore-db'
    depends_on:
      - db
    image: mongo:3.0
    volumes:
      - ./db/:/db/
